name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set image name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            labels: |
                org.opencontainers.image.title=${{ env.IMAGE_NAME }}
                org.opencontainers.image.description="This is a Docker image for the ${{ env.IMAGE_NAME }} project"
                org.opencontainers.image.url=${{ github.repositoryUrl }}
                org.opencontainers.image.source=${{ github.repositoryUrl }}
                org.opencontainers.image.version=${{ github.sha }}
                org.opencontainers.image.created=${{ github.event.repository.updated_at }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |  
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}

      - name: Docker image build and publish complete
        run: echo "Docker image built and published to GitHub Container Registry."
